In [ ]:
# TO DO TASK 4.1
#Array Creation
import numpy as np
empty_arr = np.empty((2,2))
print("1. Empty 2x2 array:\n", empty_arr)
ones_arr = np.ones((4,2))
print("\n 2. Ones 4x2 array:\n", ones_arr)
full_arr = np.full((3, 3), 7)
print("\n3. Full 3x3 array with value 7:\n", full_arr)
sample_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(sample_arr)
print("\n4. Zeros like sample array:\n", zeros_like_arr)
ones_like_arr = np.ones_like(sample_arr)
print("\n5. Ones like sample array:\n", ones_like_arr)
new_list = [1, 2, 3, 4]
list_to_array = np.array(new_list)
print("\n6. List to numpy array:\n", list_to_array)


1. Empty 2x2 array:
 [[4.38626826e-316 0.00000000e+000]
 [1.25990592e-300 1.39067116e-309]]

 2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3x3 array with value 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like sample array:
 [[0 0 0]
 [0 0 0]]

5. Ones like sample array:
 [[1 1 1]
 [1 1 1]]

6. List to numpy array:
 [1 2 3 4]


In [ ]:
#TO DO TASK PROBLEM 2
#Array Manipulation: Numerical Ranges and Array indexing:
#1 Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
2 # Create a 3X3 matrix with values ranging from 0 to 8. {Hint:look for np.reshape()}
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Create a 3X3 identity matrix.{Hint:np.eye()}
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
rand_arr = np.random.random(30)
print("Array:", rand_arr)
print("Mean:", rand_arr.mean())


Array: [0.05710896 0.04634168 0.13892133 0.35580813 0.18717832 0.96848777
 0.23883274 0.26275432 0.59338625 0.49170206 0.8410119  0.59281006
 0.15340098 0.0463788  0.53477485 0.22309722 0.85780059 0.0927401
 0.04963971 0.65538321 0.20955461 0.35683369 0.15251708 0.30012222
 0.18880898 0.77681337 0.83084335 0.4289648  0.10875404 0.7697965 ]
Mean: 0.38368558640392536


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.
arr = np.random.random((10, 10))
print("Min:", arr.min())
print("Max:", arr.max())


Min: 0.00968298369159526
Max: 0.9974367234604312


In [ ]:
#6. Create a zero array of size 10 and replace 5th element with 1.
arr = np.zeros(10)
arr[4] = 1
print(arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7. Reverse an array arr = [1,2,0,0,4,0].
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checker = np.zeros((8, 8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#problem -3 : Array Operation

x = np.array([[1, 2],[3, 5]])

y = np.array([[5, 6],[7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

print("1. Addition (x + y):")
print(x + y)
print()

print("2. Subtraction (x - y):")
print(x - y)
print()

print("3. Multiply x with any integer (example: 3):")
print(x * 3)
print()

print("4. Square of each element of x:")
print(x ** 2)
print()

print("5a. Dot product of v and w:")
print(np.dot(v, w))
print()

print("5b. Dot product of x and v:")
print(np.dot(x, v))
print()

print("5c. Dot product of x and y:")
print(np.dot(x, y))
print()

print("6a. Concatenate x and y along rows:")
print(np.vstack((x, y)))
print()

print("6b. Concatenate v and w along columns:")
print(np.column_stack((v, w)))
print()

print("7. Concatenate x and v :")
try:
    print(np.concatenate((x, v)))
except Exception as e:
    print("Error:", e)
    print("Reason: x is 2D and v is 1D. Dimensions do not match.")

#Problem - 4: Matrix Operations:
A = np.array([[3, 4],[7, 8]])

B = np.array([[5, 3],[2, 1]])

print("A =\n", A)
print("B =\n", B)
print()

A_inv = np.linalg.inv(A)
result1 = np.dot(A, A_inv)

print("1. A · A^-1 =")
print(result1)
print("=> This is the Identity Matrix, so A · A^-1 = I.")
print()


AB = np.dot(A, B)
BA = np.dot(B, A)

print("2. AB =")
print(AB)
print("BA =")
print(BA)
print("=> AB ≠ BA, so matrix multiplication is not commutative.")
print()


left_side = AB.T
right_side = np.dot(B.T, A.T)

print("3. (AB)^T =")
print(left_side)
print("B^T · A^T =")
print(right_side)
print("=> Both are equal, so (AB)^T = B^T A^T is TRUE.")


1. Addition (x + y):
[[ 6  8]
 [10 13]]

2. Subtraction (x - y):
[[-4 -4]
 [-4 -3]]

3. Multiply x with any integer (example: 3):
[[ 3  6]
 [ 9 15]]

4. Square of each element of x:
[[ 1  4]
 [ 9 25]]

5a. Dot product of v and w:
219

5b. Dot product of x and v:
[29 77]

5c. Dot product of x and y:
[[19 22]
 [50 58]]

6a. Concatenate x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

6b. Concatenate v and w along columns:
[[ 9 11]
 [10 12]]

7. Concatenate x and v :
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x is 2D and v is 1D. Dimensions do not match.
A =
 [[3 4]
 [7 8]]
B =
 [[5 3]
 [2 1]]

1. A · A^-1 =
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
=> This is the Identity Matrix, so A · A^-1 = I.

2. AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
=> AB ≠ BA, so matrix multiplication is not commutative.

3. (AB)^T =
[[23 51]
 [13 29]]
B^T · A^T =

In [ ]:
#Solve the following system of Linear equation using Inverse Methods.2x − 3y + z = −1,x − y + 2z = −3,3x + y − z = 9

A2 = np.array([[ 2, -3,  1],[ 1, -1,  2],[ 3,  1, -1]])

# Constant matrix B
B2 = np.array([-1, -3, 9])

print("Coefficient Matrix A2 =\n", A2)
print("Constant Matrix B2 =\n", B2)
print()

A2_inv = np.linalg.inv(A2)

X = np.dot(A2_inv, B2)

print("Solution using Inverse Method (X = A^-1 · B):")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Coefficient Matrix A2 =
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constant Matrix B2 =
 [-1 -3  9]

Solution using Inverse Method (X = A^-1 · B):
x = 2.0
y = 1.0
z = -2.0


In [ ]:
#4.2 Experiment: How Fast is Numpy?
#1. Element-wise Addition:• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time
import numpy as np

# Python List Addition

list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")

Python List Addition Time: 0.1296238899230957 seconds


In [ ]:
# NumPy Array Addition

arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()

print("NumPy Array Addition Time:", end - start, "seconds")


NumPy Array Addition Time: 0.004484415054321289 seconds


In [ ]:
#Element-wise Multiplication
#Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-sure and Print the time taken for this operation.
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
# Python List Multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")


Python List Multiplication Time: 0.13956856727600098 seconds


In [ ]:
# NumPy Array Multiplication

start = time.time()
arr_mul = arr1 * arr2
end = time.time()

print("NumPy Array Multiplication Time:", end - start, "seconds")

NumPy Array Multiplication Time: 0.009733915328979492 seconds


In [ ]:
#Dot Product
#Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for thisoperation.
# Python List Dot Product

start = time.time()
dot_list = sum([list1[i] * list2[i] for i in range(1_000_000)])
end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")

Python List Dot Product Time: 0.1678314208984375 seconds


In [ ]:
# NumPy Array Dot Product
start = time.time()
dot_numpy = np.dot(arr1, arr2)
end = time.time()

print("NumPy Array Dot Product Time:", end - start, "seconds")

NumPy Array Dot Product Time: 0.002301931381225586 seconds


In [ ]:
#Matrix Multiplication
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
# Python List Matrix Multiplication

import random
import time

# Generating 1000x1000 matrix using lists
A = [[random.random() for _ in range(1000)] for _ in range(1000)]
B = [[random.random() for _ in range(1000)] for _ in range(1000)]

# Function to multiply two matrices using lists
def python_matrix_multiply(A, B):
    result = [[0]*len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

start = time.time()
result_list_matrix = python_matrix_multiply(A, B)
end = time.time()

print("Python List Matrix Multiplication Time:", end - start, "seconds")

KeyboardInterrupt: 

In [ ]:
#Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-sure and print the time taken for this operation.

# NumPy Matrix Multiplication

A_np = np.random.rand(1000, 1000)
B_np = np.random.rand(1000, 1000)

start = time.time()
result_np_matrix = np.dot(A_np, B_np)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

NumPy Matrix Multiplication Time: 0.06767988204956055 seconds
